//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tthtml {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class eng_script {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal eng_script() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tthtml.eng_script", typeof(eng_script).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Text To HTML.
        /// </summary>
        internal static string str_aboutbt {
            get {
                return ResourceManager.GetString("str_aboutbt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string str_bold {
            get {
                return ResourceManager.GetString("str_bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML 5 Doctype Declaration (recommended).
        /// </summary>
        internal static string str_checkbox {
            get {
                return ResourceManager.GetString("str_checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert &gt;&gt;.
        /// </summary>
        internal static string str_convert {
            get {
                return ResourceManager.GetString("str_convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string str_exit {
            get {
                return ResourceManager.GetString("str_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string str_file {
            get {
                return ResourceManager.GetString("str_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a project that I made to simplify making webpage documentation.
        ///
        ///This program converts your text into a full-on HTML webpage.
        ///
        ///To make a new line, type &lt;br&gt; or hit Enter.
        ///
        ///To bold a text, type &lt;b&gt;your text here&lt;/b&gt; which produces &quot;your text here&quot; in a bold font.
        ///
        ///To italic a text, type &lt;i&gt;your text here&lt;/i&gt; which produces &quot;your text here&quot; in an italic font.
        ///
        ///For bold and italic, you can also use the Bold and Italic buttons.
        ///
        ///To underline a text, type &lt;u&gt;your text here&lt;/u&gt; which produces  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string str_instructions {
            get {
                return ResourceManager.GetString("str_instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string str_italic {
            get {
                return ResourceManager.GetString("str_italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string str_new {
            get {
                return ResourceManager.GetString("str_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string str_open {
            get {
                return ResourceManager.GetString("str_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string str_save {
            get {
                return ResourceManager.GetString("str_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your text here.
        /// </summary>
        internal static string str_texthere {
            get {
                return ResourceManager.GetString("str_texthere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page title.
        /// </summary>
        internal static string str_title {
            get {
                return ResourceManager.GetString("str_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unused.
        /// </summary>
        internal static string str_tranbeg {
            get {
                return ResourceManager.GetString("str_tranbeg", resourceCulture);
            }
        }
    }
}
