//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tthtml {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pol_script {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pol_script() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tthtml.pol_script", typeof(pol_script).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O programie Text To HTML.
        /// </summary>
        internal static string str_aboutbt {
            get {
                return ResourceManager.GetString("str_aboutbt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogrubione.
        /// </summary>
        internal static string str_bold {
            get {
                return ResourceManager.GetString("str_bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deklaracja Doctype HTML5 (zalecane).
        /// </summary>
        internal static string str_checkbox {
            get {
                return ResourceManager.GetString("str_checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konwertuj &gt;&gt;.
        /// </summary>
        internal static string str_convert {
            get {
                return ResourceManager.GetString("str_convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zakończ.
        /// </summary>
        internal static string str_exit {
            get {
                return ResourceManager.GetString("str_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plik.
        /// </summary>
        internal static string str_file {
            get {
                return ResourceManager.GetString("str_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To jest projekt, który zrobiłem, żeby zrobić robienie stron internetowych łatwiejsze.
        ///
        ///Ten program konwertuje twój tekst na kod strony internetowej.
        ///
        ///Aby zrobić nową linię, możesz wpisać &lt;br&gt;, albo nacisnąć przycisk Enter.
        ///
        ///Aby pogrubić tekst, napisz &lt;b&gt;twój tekst&lt;/b&gt;, co produkuje &quot;twój tekst&quot; w pogrubionej czcionce.
        ///
        ///Aby tekst był kursywą, napisz &lt;i&gt;twój tekst&lt;/i&gt;, co produkuje &quot;twój tekst&quot; w kursywej czcionce.
        ///
        ///Na pogrubienie i kursywę, możesz też użyć przycisków pod przyciskiem Konwertuj.
        ///
        ///A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string str_instructions {
            get {
                return ResourceManager.GetString("str_instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pochyła.
        /// </summary>
        internal static string str_italic {
            get {
                return ResourceManager.GetString("str_italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy.
        /// </summary>
        internal static string str_new {
            get {
                return ResourceManager.GetString("str_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otwórz.
        /// </summary>
        internal static string str_open {
            get {
                return ResourceManager.GetString("str_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz.
        /// </summary>
        internal static string str_save {
            get {
                return ResourceManager.GetString("str_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twój tekst.
        /// </summary>
        internal static string str_texthere {
            get {
                return ResourceManager.GetString("str_texthere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tytuł strony.
        /// </summary>
        internal static string str_title {
            get {
                return ResourceManager.GetString("str_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unused.
        /// </summary>
        internal static string str_tranbeg {
            get {
                return ResourceManager.GetString("str_tranbeg", resourceCulture);
            }
        }
    }
}
